services:
  ##########################################################
  # SERVICE 1: MBSYNC (for Syncing emails from IMAP to Maildir)
  ##########################################################
  mbsync:
    image: alpine:3.21
    env_file: .env
    environment:
      - DRY_RUN=${DRY_RUN:-false}
    volumes:
      - ./data/maildir:/maildir
    working_dir: /maildir
    command: |
      sh -c "
        apk add --no-cache isync &&
        mkdir -p /maildir/INBOX/{cur,new,tmp} &&
        echo 'DEBUG: DRY_RUN environment variable = [$DRY_RUN]' &&
        if [ \"$DRY_RUN\" = \"true\" ]; then
          echo '=== MBSYNC DRY-RUN MODE: SIMULATION ONLY - NO ACTUAL CHANGES ===' &&
          mbsync --dry-run --verbose -c /maildir/.mbsyncrc -a &&
          echo '=== DRY-RUN COMPLETE: NO FILES WERE MODIFIED ==='
        else
          echo '=== MBSYNC LIVE MODE: ACTUAL SYNC OPERATION ===' &&
          mbsync --verbose -c /maildir/.mbsyncrc -a
        fi
      "

  ##########################################################
  # SERVICE 2: NOTMUCH WEB (for Viewing and Searching)
  ##########################################################
  notmuch-web:
    image: anarcat/notmuch-web
    restart: unless-stopped
    ports:
      - "8090:8000"
    env_file: .env
    environment:
      - NOTMUCH_WEB_USER=${WEB_USER}
      - NOTMUCH_WEB_PASSWORD=${WEB_PASSWORD}
    volumes:
      - ./data/maildir:/home/user/mail:ro
      - ./data/notmuch:/home/user/.notmuch
    command: >
      sh -c "notmuch setup && notmuch-web --host=0.0.0.0"

  ##########################################################
  # SERVICE 3: RCLONE (for Off-site Backups)
  ##########################################################
  rclone:
    image: rclone/rclone:latest
    env_file: .env
    environment:
      - RCLONE_CONFIG_B2_TYPE=b2
      - RCLONE_CONFIG_B2_ACCOUNT=${B2_ACCOUNT_ID}
      - RCLONE_CONFIG_B2_KEY=${B2_APPLICATION_KEY}
      - DRY_RUN=${DRY_RUN:-false}
    volumes:
      - ./data/maildir:/data/maildir:ro
    command: sh -c "if [ \"$DRY_RUN\" = \"true\" ]; then rclone sync /data/maildir \"b2:${B2_BUCKET_NAME}/email-archive\" --fast-list --dry-run; else rclone sync /data/maildir \"b2:${B2_BUCKET_NAME}/email-archive\" --fast-list; fi"

  ##########################################################
  # SERVICE 4: PYTHON PRUNE (for Pruning old emails from IMAP)
  ##########################################################
  prune-imap:
    image: python:3.11-alpine
    env_file: .env
    environment:
      - CUTOFF_DATE=${CUTOFF_DATE}
      - DRY_RUN=${DRY_RUN:-false}
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    command: sh -c "if [ \"$DRY_RUN\" = \"true\" ]; then python prune_imap.py --dry-run; else python prune_imap.py; fi" 