services:
  dovecot:
    image: ghcr.io/tiredofit/docker-dovecot:latest
    restart: unless-stopped
    volumes:
      - /srv/docker-data/mail/archive:/srv/mail/archive:ro
      - /srv/docker-data/mail/dovecot/index:/var/dovecot/index:rw
      - /srv/docker-data/mail/dovecot/control:/var/dovecot/control:rw
      - /srv/docker-data/mail/config/dovecot:/etc/dovecot:ro
    # No public ports; only internal network access for Roundcube

  roundcube:
    image: roundcube/roundcubemail:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - ROUNDCUBE_DEFAULT_HOST=dovecot
      - ROUNDCUBE_DEFAULT_PORT=143
      - ROUNDCUBE_DB_TYPE=sqlite
      - ROUNDCUBE_DB_PATH=/var/roundcube/db/sqlite.db
    volumes:
      - /srv/docker-data/mail/roundcube/db:/var/roundcube/db:rw
      - /srv/docker-data/mail/config/roundcube:/var/roundcube/config:ro
    depends_on:
      - dovecot

  mbsync:
    image: alpine:3.21
    env_file: .env
    environment:
      - DRY_RUN=${DRY_RUN:-false}
    volumes:
      - /srv/docker-data/mail/archive:/srv/mail/archive:rw
      - /srv/docker-data/mail/state/mbsync:/var/lib/mbsync:rw
      - /srv/docker-data/mail/config/mbsync:/etc/mbsync:ro
    secrets:
      - yahoo_app_password
    working_dir: /srv/mail/archive
    command: |
      sh -c "
        apk add --no-cache isync &&
        mkdir -p /srv/mail/archive/INBOX/{cur,new,tmp} &&
        echo 'DEBUG: DRY_RUN environment variable = [$DRY_RUN]' &&
        if [ \"$DRY_RUN\" = \"true\" ]; then
          echo '=== MBSYNC DRY-RUN MODE: SIMULATION ONLY - NO ACTUAL CHANGES ===' &&
          mbsync --dry-run --verbose -c /etc/mbsync/mbsyncrc -a &&
          echo '=== DRY-RUN COMPLETE: NO FILES WERE MODIFIED ==='
        else
          echo '=== MBSYNC LIVE MODE: ACTUAL SYNC OPERATION ===' &&
          mbsync --verbose -c /etc/mbsync/mbsyncrc -a
        fi
      "

  imapfilter:
    build: ./imapfilter
    env_file: .env
    volumes:
      - /srv/docker-data/mail/config/imapfilter:/etc/imapfilter:ro
    secrets:
      - yahoo_app_password

  rclone:
    image: rclone/rclone:latest
    env_file: .env
    environment:
      - RCLONE_CONFIG_B2_TYPE=b2
      - RCLONE_CONFIG_B2_ACCOUNT=${B2_ACCOUNT_ID}
      - RCLONE_CONFIG_B2_KEY=${B2_APPLICATION_KEY}
      - DRY_RUN=${DRY_RUN:-false}
    volumes:
      - /srv/docker-data/mail:/data:ro
      - /srv/docker-data/mail/config/rclone:/config/rclone:ro
    secrets:
      - rclone_credentials
    command: sh -c "if [ \"$DRY_RUN\" = \"true\" ]; then rclone sync /data/archive \"b2:${B2_BUCKET_NAME}/email-archive\" --fast-list --dry-run; else rclone sync /data/archive \"b2:${B2_BUCKET_NAME}/email-archive\" --fast-list; fi"

  compress:
    image: alpine:3.21
    volumes:
      - /srv/docker-data/mail/archive:/srv/mail/archive:rw
    command: ["/bin/sh", "-c", "echo 'stub compress task - plug in doveadm compress here'"]

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - mbsync
      - imapfilter
      - rclone
      - compress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

secrets:
  yahoo_app_password:
    file: /srv/docker-data/mail/secrets/yahoo_app_password
  rclone_credentials:
    file: /srv/docker-data/mail/secrets/rclone.conf